version: "3.9"

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker-demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./docker-backend
    image: vaibhavpatelpromact/backend:latest
    container_name: docker-be
    ports:
      - "47430:47430"
    environment:
      ASPNETCORE_URLS: "http://+:47430"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=host.docker.internal;Port=5432;Database=docker-demo;Username=postgres;Password=postgres"
      # TestingString: "Heyyy!! this is from appsettings.json file."
    depends_on:
      - db

  frontend:
    build: ./docker-frontend
    image: vaibhavpatelpromact/frontend:latest
    container_name: docker-fe
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: